services:
  - type: web
    name: wiki-proyect
    runtime: ruby
    buildCommand: "./bin/render-build.sh"
    startCommand: "bundle exec puma -C config/puma.rb"
    env: ruby
    port: 3000  # ← Añade esta línea
    envVars:
      - key: PORT
        value: 3000  # Opcional pero recomendado
      - key: RAILS_MASTER_KEY
        sync: false